version: "3.9"
services:
  prod-web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - PORT=3002
    networks:
      - nextjs_network
  nginx-nextjs:
    build: ./nginx
    ports:
      - 80:80
    environment:
      PORT: 3002

networks:
  nextjs_network:
    driver: bridge
